#PostgreSQL Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Brevo API Email Configuration
brevo.api.key=${BREVO_API_KEY}
brevo.from.email=${BREVO_FROM_EMAIL}
brevo.from.name=${BREVO_FROM_NAME}

# JWT Secret Key
jwt.secret=${JWT_SECRET}

xpenso.frontend.url=${XPENSO_FRONTEND_URL}

app.activation.url=${XPENSO_BACKEND_URL}

app.return.activation.link=false